### ISSUE TITLE
Buttons are not reactive to hover

### ISSUE THREAD

**Issue by Speedysays01** [aakki16/Blnkoo#16]
The buttons on the landing page are not responding to mouse hovers or click actions. I can make them respond to mouse activity enhancing the UI as well as UX of the site.
Please assign me this issue under Hacktoberfest 2024

**Comment by aakki16** [comment]
ok you can contribute now 🤝

**Comment by Speedysays01** [comment]
Thanks! I have created the PR kindly review it.
