### ISSUE TITLE
Copy all code button missing

### ISSUE THREAD

**Issue by rko0211** [aakki16/Blnkoo#17]
**Is your feature request related to a problem? Please describe.**
So, when user wants to use cdn link or any other link in their project for that they have to copy the cdn link, at present copy all button is not their users have to select code link manually .

**Describe the solution you'd like**
SO i want to add copy buttons for each link.

**Describe alternatives you've considered**

**Additional context**
![feature1](https://github.com/user-attachments/assets/3a2d9e6e-3f78-4f3d-96b8-89d5eb84f983)

So, kindly assign me this task under **hacktoberfest** 2024

**Comment by aakki16** [comment]
You can contribute
