### ISSUE TITLE
Add functionality uppercase & lowercase 

### ISSUE THREAD

**Issue by aakki16** [aakki16/Blnkoo#6]
Add functionality uppercase and lowercase in css file 
Location:- **dist/csss/blnkoo.css**

Also must remember to create this type text-uppercase, lowercase class and if any case you have besy sutable classname work so also use 🤗.

Free feel to contribute.

**Comment by ShadowFax1731** [comment]
Can you please assign this to me? I can work on this. Thanks.

**Comment by aakki16** [comment]
Please give star and contribute 😇

**Comment by aakki16** [comment]
👋 complete this issue now?

**Comment by samarthkumar008** [comment]
I complete #11
