### ISSUE TITLE
Height & Width

### ISSUE THREAD

**Issue by aakki16** [aakki16/Blnkoo#7]
Hello Everyone,

Create height &  width supports .h- and .w- with the values of 25, 50, 75, 100, auto and must also half page and full page height(vh).

**Comment by ShadowFax1731** [comment]
What do the values of 25, 50, 75 and 100 signify? Is it pixels or rem? Can you clarify further, please ? I would like to contribute to this.

**Comment by aakki16** [comment]
This values in pixels or percentage both.

**Comment by ShadowFax1731** [comment]
Raised the PR. Kindly Check.
